import apiClient from "./client";

export interface Sprint {
  id: number;
  name: string;
  start_date: string;
  end_date: string;
  goal: string | null;
  project_id: number;
  is_active: boolean;
}

export interface User {
    id: number;
    name: string;
    email: string;
}

export interface Comment {
    id: number;
    content: string;
    task_id: number;
    author_id: number;
    created_at: string;
    author: User | null;
}

export interface Subtask {
    id: number;
    title: string;
    is_completed: boolean;
    task_id: number;
}

export interface Task {
  id: number;
  title: string;
  description: string | null;
  status: string; // "TODO", "IN_PROGRESS", "REVIEW", "QA", "DONE"
  project_id: number;
  sprint_id: number | null;
  assignee_id: number | null;
  story_points: number | null;
  attachment_url: string | null;
  subtasks: Subtask[];
  comments: Comment[];
}

export interface TaskCreate {
  title: string;
  description?: string;
  project_id: number;
  sprint_id?: number | null;
  assignee_id?: number | null;
  story_points?: number | null;
  attachment_url?: string | null;
}

// Sprints
export const getActiveSprint = async (projectId: number): Promise<Sprint | null> => {
  try {
    const response = await apiClient.get<Sprint>(`/api/v1/sprints/active?project_id=${projectId}`);
    return response.data;
  } catch (error: any) {
    if (error.response && error.response.status === 404) {
        return null;
    }
    throw error;
  }
};

export const createSprint = async (data: Omit<Sprint, "id">): Promise<Sprint> => {
  const response = await apiClient.post<Sprint>("/api/v1/sprints/", data);
  return response.data;
};

export const completeSprint = async (sprintId: number): Promise<Sprint> => {
    const response = await apiClient.post<Sprint>(`/api/v1/sprints/${sprintId}/complete`);
    return response.data;
}

// Tasks
export const getTasksForSprint = async (sprintId: number): Promise<Task[]> => {
  const response = await apiClient.get<Task[]>(`/api/v1/tasks/sprint/${sprintId}`);
  return response.data;
};

export const getBacklogTasks = async (projectId: number): Promise<Task[]> => {
    const response = await apiClient.get<Task[]>(`/api/v1/tasks/backlog/${projectId}`);
    return response.data;
};

export const createTask = async (data: TaskCreate): Promise<Task> => {
  const response = await apiClient.post<Task>("/api/v1/tasks/", data);
  return response.data;
};

export const updateTaskStatus = async (taskId: number, status: string): Promise<Task> => {
  const response = await apiClient.put<Task>(`/api/v1/tasks/${taskId}/status`, { status });
  return response.data;
};

export const updateTask = async (taskId: number, data: Partial<TaskCreate>): Promise<Task> => {
  const response = await apiClient.put<Task>(`/api/v1/tasks/${taskId}`, data);
  return response.data;
};

export const deleteTask = async (taskId: number): Promise<void> => {
  await apiClient.delete(`/api/v1/tasks/${taskId}`);
};

// Comments
export const createComment = async (taskId: number, content: string): Promise<Comment> => {
    const response = await apiClient.post<Comment>(`/api/v1/tasks/${taskId}/comments`, { content });
    return response.data;
};

// Subtasks
export const createSubtask = async (taskId: number, title: string): Promise<Subtask> => {
    const response = await apiClient.post<Subtask>(`/api/v1/tasks/${taskId}/subtasks`, { title });
    return response.data;
};

export const updateSubtask = async (subtaskId: number, is_completed: boolean): Promise<Subtask> => {
    const response = await apiClient.put<Subtask>(`/api/v1/tasks/subtasks/${subtaskId}`, { is_completed });
    return response.data;
};

export const deleteSubtask = async (subtaskId: number): Promise<void> => {
    await apiClient.delete(`/api/v1/tasks/subtasks/${subtaskId}`);
};

// Reports
export interface AutoGeneratedReport {
  tasks_completed: string;
  tasks_planned: string;
}

export const autoGenerateReport = async (sprintId: number): Promise<AutoGeneratedReport> => {
  const response = await apiClient.get<AutoGeneratedReport>(`/api/v1/reports/auto-generate/${sprintId}`);
  return response.data;
};
