import apiClient from "./client";

export interface Sprint {
  id: number;
  name: string;
  start_date: string;
  end_date: string;
  goal: string | null;
  project_id: number;
  is_active: boolean;
}

export interface Task {
  id: number;
  title: string;
  description: string | null;
  status: "TODO" | "IN_PROGRESS" | "DONE" | string;
  sprint_id: number;
  assignee_id: number | null;
  story_points: number | null;
}

export interface TaskCreate {
  title: string;
  description?: string;
  sprint_id: number;
  assignee_id?: number | null;
  story_points?: number | null;
}

export const getActiveSprint = async (projectId: number): Promise<Sprint | null> => {
  try {
    const response = await apiClient.get<Sprint>(`/sprints/active?project_id=${projectId}`);
    return response.data;
  } catch (error: any) {
    if (error.response && error.response.status === 404) {
        return null;
    }
    throw error;
  }
};

export const createSprint = async (data: Omit<Sprint, "id">): Promise<Sprint> => {
  const response = await apiClient.post<Sprint>("/sprints/", data);
  return response.data;
};

export const getTasksForSprint = async (sprintId: number): Promise<Task[]> => {
  const response = await apiClient.get<Task[]>(`/tasks/sprint/${sprintId}`);
  return response.data;
};

export const createTask = async (data: TaskCreate): Promise<Task> => {
  const response = await apiClient.post<Task>("/tasks/", data);
  return response.data;
};

export const updateTaskStatus = async (taskId: number, status: string): Promise<Task> => {
  const response = await apiClient.put<Task>(`/tasks/${taskId}/status`, { status });
  return response.data;
};

export interface AutoGeneratedReport {
  tasks_completed: string;
  tasks_planned: string;
}

export const autoGenerateReport = async (sprintId: number): Promise<AutoGeneratedReport> => {
  const response = await apiClient.get<AutoGeneratedReport>(`/reports/auto-generate/${sprintId}`);
  return response.data;
};
