export const AUTH_TAGS = {
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
};

export const MASTER_DATA = {
  PROGRAM_CATEGORY: {
    LIST: "PROGRAM-CATEGORY-LIST",
  },
  PROGRAM_TYPE: {
    LIST: "PROGRAM-TYPE-LIST",
  },
  PROGRAM_SUBTYPE: {
    LIST: "PROGRAM-SUBTYPE-LIST",
  },
  MODULE_BASKET_TYPE: {
    LIST: "MODULE-BASKET-TYPE-LIST",
  },
  CLASS_ROOM: {
    LIST: "CLASS-ROOM-LIST",
  },
  RESOURCE_PERSON_TYPE: {
    LIST: "RESOURCE-PERSON-TYPE-LIST",
  },
  SERVICE: {
    LIST: "SERVICE-LIST",
  },
  EDUCATIONAL_QUALIFICATION_LEVEL: {
    LIST: "EDUCATIONAL-QUALIFICATION-LEVEL-LIST",
  },
  MODULE_GROUP: {
    LIST: "MODULE-GROUP-LIST",
  },
  SUBJECT_AREA: {
    LIST: "SUBJECT-AREA-LIST",
  },
};
